@urlApi = http://localhost:5000

### get all products
GET {{urlApi}}/products

### get name a product
GET {{urlApi}}/products?name=boca

### banear single user
POST {{urlApi}}/products/642237fc8186e2e058d00515


### create a product
POST {{urlApi}}/products
Content-Type: application/json

{
 "name":"Adidas Women's Casual Running Shoe",
 "image":["https://m.media-amazon.com/images/I/81zc8i+8qfL._AC_UX679_.jpg","https://m.media-amazon.com/images/I/71q3fQj8KjL._AC_UY500_.jpg", "https://m.media-amazon.com/images/I/61GHYB6wuNL._AC_UX522_.jpg"],
 "price":36.73,
  "user":"642adccfcc3e57ada68f51d3",
 "discount":0,
 "description":"Explore your surroundings. These adidas running-inspired shoes feature a foot-hugging knit upper and a female-friendly fit. Soft midsole cushioning adds comfort as you head out for coffee or discover a busy side street.",
 "season":2021 ,
 "size":[{"6'5":3}, {"6'6":5} , {"7":12} ],
 "category": "footwear",
 "gender":"women",
 "state":"new",
 "brands":"ADIDAS"
}