@urlApi = http://localhost:5000

### get all users
GET {{urlApi}}/users

### get name a users
GET {{urlApi}}/users?name=Juan

### create a user
POST {{urlApi}}/users
Content-Type: application/json

{
  "name":"Carlo Alberto",
  "eMail":"albertosuarez@gmail.com",
  "lastName":"Suarez Perez",
  "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq7dDqaApR0N2jhw8SQglWnx41KEY1P1D1cg&usqp=CAU"
}

### get single user id
GET {{urlApi}}/users/641cc89444400c0d8a723244

### banear single user
POST {{urlApi}}/users/6428a374de408ecca1645d36

### update a user
PUT {{urlApi}}/users/642383a9afc7672526531bdd
Content-Type: application/json

{
  "roll":"superAdmin"
}


### favorite a user
POST {{urlApi}}/users/favorite
Content-Type: application/json

{
  "user":"642a18f86d9763044626471f",
  "product":"642a37d06d9763044626479b" 
}