@urlApi = http://localhost:5000

### get all products
GET {{urlApi}}/products

### get name a product
GET {{urlApi}}/products?name=

### create a product
POST {{urlApi}}/products
Content-Type: application/json

{
  "name":"camiseta retro argentina 86",
 "image":["https://http2.mlstatic.com/D_NQ_NP_646753-CBT53904382894_022023-V.jpg","https://i.pinimg.com/originals/f2/c2/b9/f2c2b9ff28162035746c8e5a1fe1b3b5.jpg","https://http2.mlstatic.com/D_NQ_NP_739726-MLA49972629880_052022-O.jpg"],
 "price":22.99,
 "discount":0,
 "description":"Camiseta Argentina  Titular Homenaje 86",
 "store":"641ce9e6defd52f01bc596e1",
 "season":1986 ,
 "size":"M" 
}